<?php

namespace app\common\controller;

use think\Controller;
use think\Request;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub


        // 定义常量user_id
        define('USER_ID' , session('user_id'));

    }

    /**
     * 检查用户是否已经登录
     */
    public function checkAdminLoged()
    {
        if(!USER_ID)
        {
            $this->error('管理员未登录！禁止访问！', url('index/admin/login'));
        }
    }

    /**
 * 检查用户是否已经登录
 */
    public function checkUserLoged()
    {
        if(!USER_ID)
        {
            $this->error('用户未登录！禁止访问！', url('index/user/login'));
        }
    }

    /**
     * 不准管理员二次登陆
     */
    public function checkAdminLoginStatus()
    {
        if(USER_ID)
        {
            $this->error('管理员已经登录，请勿重复登录,正在跳转用户中心！', url('index/admin/index'));
        }
    }

    /**
     * 不准用户二次登陆
     */
    public function checkLoginStatus()
    {
        if(USER_ID)
        {
            $this->error('用户已经登录，请勿重复登录,正在跳转用户中心！', url('index/user/index'));
        }
    }
}
